config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'homes#top'
  get 'homes/about' => "homes#about"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :create, :edit, :update] do
    get "users/follower" => "users#follower"
    get "users/followed" => "users#followed"
    get "users/favorites" => "users#favorites"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :inquiries, only: [:new, :create]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]

  delete '/notification/destroy_all' => 'notifications#destroy_all'
end

app/models/notification.rb
class Notification < ApplicationRecord
  scope :active, -> { order(created_at: :desc) }
  # default_scopeでデフォルトで並び順を作成日降順にしてるので常に新しい通知からデータから取ってこれる

  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
  # optional:trueでnillを許可
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(15)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    @visiter = notification.visiter
    @comment = nil
    @your_post = link_to 'あなたの投稿', users_path(notification), style: "font-weight: bold;"
    @visiter_comment = notification.post_comment_id

    case notification.action
    when "follow"
      tag.a(notification.visiter.name, href: users_path(@visiter),
                                       style: "font-weight: bold;") + "があなたをフォローしました"
    when "favorite"
      tag.a(notification.visiter.name, href: user_path(@visiter),
                                       style: "font-weight: bold;") + "が" +
                                       tag.a('あなたの投稿', href: post_path(notification.post_id),
                                                       style: "font-weight: bold;") + "にいいねしました"
    when "comment" then
      @comment = PostComment.find_by(id: @visiter_comment)&.comment
      tag.a(@visiter.name, href: user_path(@visiter),
                           style: "font-weight: bold;") + "が" +
                           tag.a('あなたの投稿', href: post_path(notification.post_id),
                                           style: "font-weight: bold;") + "コメントしました"
    end
  end

  def unchecked_notifications
    @notification = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% item = notification.post %>

<div class="user-view clearfix">
  <%= link_to user_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill,100,100, format: "jpeg", fallback: "no_image.jpeg", size: "50x50", class:"profile_img-circle" %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= "(#{time_ago_in_words(notification.created_at)} 前)" %></span>
  <br><hr>
  <% if !@comment.nil? %>
    <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<h3 class="text-center">通知</h3>
 <div class="container">
  <%= link_to notification_destroy_all_path, method: :delete do %>
    <i class="fas fa-trash" style="color: black;"></i>
    <h7 style="color: black;">全削除</h7>
  <% end %>
  <hr>
  <% if @notifications.exists? %>
  <div class="user-index" style="text-align: center;">
    <%= render @notifications %>
  </div>
  <% else %>
    <p>通知はありません</p>
  <% end %>
 </div>
 <%= paginate @notifications %>