config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'homes#top'
  get 'homes/about' => "homes#about"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :create, :edit, :update] do
    get "users/follower" => "users#follower"
    get "users/followed" => "users#followed"
    get "users/favorites" => "users#favorites"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :inquiries, only: [:new, :create]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]

  delete '/notification/destroy_all' => 'notifications#destroy_all'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  attachment :profile_image

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :follower_user, through: :followed, source: :follower
  has_many :following_user, through: :follower, source: :followed
  # foreign_keyは入口  sourceは出口

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :room, through: :user_rooms

  has_many :active_notifications, class_name: "Notification",
                                  foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
                                   foreign_key: "visited_id", dependent: :destroy

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # すでにフォロー済みであればtrue返す
  def following?(user)
    following_user.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def create_notification_follow!(current_user)
    # 同じ通知が存在しない時だけレコードを作成
    temp = Notification.where([
      "visiter_id = ? and visited_id = ? and action = ? ",
      current_user.id, id, 'follow',
    ])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: [:create]

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: [:update, :destroy]

  def create
    super
    # byebug
    UserMailer.registration_confirmation(resource).deliver unless resource.invalid?
    # UserMailer.registration_confirmation.deliver
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def new_guest
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search = User.ransack(params[:q])
    @users = @search.result(distinct: true).order(created_at: "DESC").page(params[:page]).per(10)
    @all_ranks = Post.find(Favorite.group(:post_id).
    order(Arel.sql('count(post_id) desc')).limit(3).pluck(:post_id))
  end

  def show
    @user = User.find(params[:id])
    @favorite_posts = @user.favorite_posts
    @posts = @user.posts.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集が完了しました。"
      redirect_to user_path(@user.id)
    else
      flash[:alert] = "内容を入力してください。"
      render :edit
    end
  end

  def follower
    @user = User.find(params[:user_id])
    @users = @user.follower_user.page(params[:page]).per(10)
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.following_user.page(params[:page]).per(10)
  end

  def favorites
    @user = User.find(params[:user_id])
    @favorite = @user.favorite_posts.page(params[:page]).per(10)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "primary"
    when "error"
      "danger"
    end
  end
end

app/views/users/_index.html.erb
<%= search_form_for @search, url: users_path do |f| %>
<div class="flex-container">
 <div class="search">
     <%= f.search_field :name_cont, placeholder: "ユーザー名を検索...", size: "40", class: "form-control" %></div>
     <%= f.submit '検索', class: "btn btn-primary" %>
     <% end %>
</div>
 <div class="white">
  <div class="col-12 ml-1">
   <table class="table table-hover">
    <tbody>
     <tr>
      <% users.each do |user| %>
          <td><%= link_to user.name, user_path(user.id) -%></td>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
          <td>フォロー数：<%= user.follower.count %></td>
          <td>フォロワー数：<%= user.followed.count %></td>
          <td>
             <% unless current_user == user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", unfollow_path(user.id), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "フォローする", follow_path(user.id), method: :POST, class: "btn btn-success" %>
                <% end %>
             <% end %>
          </td>
    </tr>
    <% end %>
   </tbody>
 </table>
<%= paginate users %>
 </div>
</div>

app/views/users/_info.html.erb
<table class='table'>
  <tr>
    <th><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
    </tr>
  <tr>
	  <th>名前</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
    <% user ||= current_user %>
    <th>フォロー</th>
    <th><%= link_to user.follower.count, user_users_followed_path(user.id) %></th>
  </tr>
  <tr>
    <th>フォロワー</th>
    <th><%= link_to user.followed.count, user_users_follower_path(user.id) %></th>
  </tr>
  <tr>
    <th>いいねした投稿</th>
　  <th><%= link_to user.favorites.count, user_users_favorites_path(user.id) %></th>
  </tr>
</table>

app/views/users/edit.html.erb
<div class="container">
  <%= form_with model:@user, local:true do |f| %>
  <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
    <h3 style="padding: 30px;">プロフィール編集</h3>
    <button type="button" class="btn btn-outline-light rounded-pill">
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </button>
  </div>
  <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
    <%= f.label :name, "名前" %><br>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前",class: "form-control" %>
  </div>
  <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
    <%= f.label :email, "自己紹介" %><br>
    <%= f.text_field :introduction, autofocus: true, id:"inputintroduction", placeholder:"好きな選手など、、、",class: "form-control" %>
  </div>
  <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
    <%= f.submit "変更を保存", class: "btn btn-primary" %>
  </div>
  <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
  <%= link_to "パスワード変更などはこちらから", edit_user_registration_path, class: "btn btn-dark" %>
  <% end %>
  </div>
<%= link_to :back do %><div style="color: black;">
  <i class="fas fa-undo-alt">戻る</i></div>
  <% end %>
</div>

app/views/users/favorites.html.erb
<div class="container">
<p class="row justify-content-center" style="padding-top: 20px;"><i class="fas fa-heart" style="color: red;"></i>いいねした投稿</p>
<div class="col-12 ml-1">
<% @favorite.each do |f_post| %>
<div class="card text-center">
  <div class="card-header">
      <%= attachment_image_tag f_post.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" -%>
  <%= link_to f_post.user.name, user_path(f_post.user) -%>さんが
     <%= l f_post.created_at %>に投稿</div>
  <div class="card-body">
    <h5 class="card-title" style="font-weight: bold;"><%= link_to f_post.title, post_path(f_post.id) -%></h5>
    <p class="card-text"><%= f_post.body.truncate(100) -%>
        <% if f_post.body.size >= 10 -%>
        <%= link_to post_path(f_post.id) do %>
        続きを読む
        <% end %>
        <% end %></p>
  </div>
  <div class="card-footer text-muted">
<span style="padding-right: 20px;"><i class="far fa-comment-dots"></i>
  <%= link_to f_post.post_comments.count, post_path(f_post.id) %></span>
   <span id="favorite-<%= f_post.id %>">
   <%= render 'favorites/favorites', post: f_post %>
   </span>
  </div>
</div><br>
<% end %>
</div>
<%= paginate @favorite %>
</div>

app/views/users/followed.html.erb
<div class="container">
<h1 class="row justify-content-center">Follow Users</h1>
<% if @user.follower.count == 0 %>
<h4 class="row justify-content-center">フォローしている人はいません</h4>
<% else %>
  <table class='table table-hover'>
  <thead>
    <tr>
      <th>name</th>
      <th>image</th>
      <th colspan="6"></th>
    </tr>
  </thead>
<tbody>
<% @users.each do |user| %>
<div class='col-md-10 offset-md-1'>
    <tr>
    <td><%= link_to user.name, user_path(user.id) -%></td>
    <td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
    <td>フォロー数：<%= user.follower.count %></td>
    <td>フォロワー数：<%= user.followed.count %></td>
    <td>
 <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", unfollow_path(user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "フォローする", follow_path(user.id), method: :POST, class: "btn btn-success" %>
    <% end %>
 <% end %>
 </td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @users %>
<% end %>

app/views/users/follower.html.erb
<div class="container">
<h1 class="row justify-content-center">Follower Users</h1>
<% if @user.followed.count == 0 %>
<h4 class="row justify-content-center">フォロワーはいません</h4>
<% else %>
  <table class='table table-hover'>
  <thead>
    <tr>
      <th>name</th>
      <th>image</th>
      <th colspan="6"></th>
    </tr>
  </thead>
<tbody>
<% @users.each do |user| %>
<div class='col-md-10 offset-md-1'>
    <tr>
    <td><%= link_to user.name, user_path(user.id) -%></td>
    <td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
    <td>フォロー数：<%= user.follower.count %></td>
    <td>フォロワー数：<%= user.followed.count %></td>
    <td>
 <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", unfollow_path(user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "フォローする", follow_path(user.id), method: :POST, class: "btn btn-success" %>
    <% end %>
 <% end %>
 </td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @users %>
<% end %>

app/views/users/index.html.erb
<div class='container-px-5 px-sm-0'>
  <div class='row'>
    <div class='col-sm-4 col-md-2'>
     <%= render 'info', user: current_user %>
    </div>
    <div class='col-sm-4 col-md-8'>
     <%= render 'index',users: @users %>
    </div>
     <%= render 'posts/lanks', posts: @posts %>
  </div>
</div>

app/views/users/show.html.erb
<div class="layout-top">
  <div class="container">
    <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    </div>
    <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
      <%= @user.name %>
    </div>
    <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
      自己紹介 <%= @user.introduction %>
    </div>
    <% if @user.id == current_user.id %>
    <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
      <%= link_to "プロフィール編集", edit_user_path(@user) %>
    </div>
    <% end %>

    <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
    <% if current_user != @user %>
      <%= link_to 'ダイレクトメッセージ', chat_path(@user.id), class: "far fa-comments btn btn-warning" %>
    <% end %>
    </div>

    <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
  　<th><i class="fas fa-heart" style="color: red;"></i>いいねした投稿</th>
  　<th><%= link_to @user.favorites.count, user_users_favorites_path(@user.id) %></th>
  　</div>

      <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
      <% unless current_user == @user %>
       <% if current_user.following?(@user) %>
        <td>
        <%= link_to "フォロー外す", unfollow_path(@user.id), method: :delete, class: "btn btn-danger" %>
        </td>
       <% else %>
        <td>
        <%= link_to "フォローする", follow_path(@user.id), method: :POST, class: "btn btn-success" %>
        </td>
       <% end %>
      <% end %>
      </div>

      <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
        <% @user ||= current_user %>
        <th>follows</th>
        <th><%= link_to @user.follower.count, user_users_followed_path(@user.id) %></th>
      </div>

      <div class="ield form-group mt-3 text-center col-sm-6 offset-sm-3">
        <th>followers</th>
        <th><%= link_to @user.followed.count, user_users_follower_path(@user.id) %></th>
      </div>

  <p class="row justify-content-center" style="padding-top: 20px;">投稿履歴</p>
     <div class="col-12 ml-1">
       <% if @posts.count == 0 %>
      <h5 style="text-align: center;">まだ投稿がありません。投稿してみましょう！</h5>
      <% else %>
      <% @posts.each do |post| %>
    <div class="card text-center">
      <div class="card-header">
         <%= l post.created_at %>に投稿
      </div>
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bold;"><%= link_to post.title, post_path(post.id) -%></h5>
        <p class="card-text"><%= post.body.truncate(100) -%>
            <% if post.body.size >= 3 -%>
            <%= link_to post_path(post.id) do %>
            続きを読む
            <% end %>
            <% end %>
         </p>
      </div>
    <div class="card-footer text-muted">
    <span style="padding-right: 20px;"><i class="far fa-comment-dots"></i>
    <%= link_to"#{post.post_comments.count}", post_path(post.id) %></span>
     <span id="favorite-<%= post.id %>">
     <%= render 'favorites/favorites', post: post %>
     </span>
    </div>
  </div><br>
  <% end %>
  </div>
   </div>
   <% end %>
  </div>
<%= paginate @posts %>