config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'homes#top'
  get 'homes/about' => "homes#about"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :create, :edit, :update] do
    get "users/follower" => "users#follower"
    get "users/followed" => "users#followed"
    get "users/favorites" => "users#favorites"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :inquiries, only: [:new, :create]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]

  delete '/notification/destroy_all' => 'notifications#destroy_all'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships

  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tags(savepost_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      tags << post_tag
    end
  end

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorite"
    )
    notification.save if notification.valid?
    # valid？でバリデーションが実行された結果エラーが無い場合trueを返し，エラーが発生した場合falseを返す
  end

  def create_notification_comment!(current_user, post_comment_id) # 感嘆符で例外を発生させる
    # 自分以外にコメントしている人を全て取得し全員に通知送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).
      where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合投稿者に通知送る
    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )

    # 自分の投稿に対しては通知ずみとする
    if notification.visiter_id == notification.visited_id
      notification.checked == true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result(distinct: true).
      order(created_at: "DESC").includes(:user).page(params[:page]).per(10)
    if params[:tag_id].present?
      @posts = @posts.joins(:tag_relationships).
        where(tag_relationships: { tag_id: params[:tag_id] })
    end
    @all_ranks = Post.find(Favorite.group(:post_id).
      order(Arel.sql('count(post_id) desc')).limit(3).pluck(:post_id))
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:tag_ids].split(',')
    @tags = tag_list
    @post.user_id = current_user.id
    if @post.save
      @post.save_tags(tag_list)
      flash[:notice] = "投稿が完了しました。"
      redirect_to posts_path
    else
      flash[:alert] = "内容を入力してください。"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(",")
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:tag_ids].split(',')
    if @post.update_attributes(post_params)
      @post.save_tags(tag_list)
      flash[:notice] = '投稿を編集しました‼'
      redirect_to @post
    else
      flash[:alert] = "内容が正しくありません。"
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<%= search_form_for @search, url: posts_path do |f| %>
<div class="flex-container">
 <div class="search">
  <%= f.search_field :title_cont, placeholder: "投稿タイトル、本文で検索", class: "form-control" %></div>
  <%= f.submit '検索', class: "btn btn-primary" %>
  <% end %>
</div>
<div class="tag_search">
 <i class="fas fa-tags" style="margin: 0 auto;"></i>タグで絞り込む
 <%= form_with url: posts_path, method: :get, class: 'tag_search' do %>
  <%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
    {prompt: 'タグで絞り込む', onchange: 'submit(this.form);', class: "form-control"}%>
 <% end %>
</div>
 <div class="col-12 ml-1">
  <% posts.each do |post| %>
   <div class="card text-center">
    <div class="card-header">
     <%= attachment_image_tag post.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" -%>
     <%= link_to post.user.name, user_path(post.user) -%>さんが
     <%= l post.created_at %>に投稿
    </div>
  <div class="card-body">
    <h5 class="card-title" style="font-weight: bold;"><%= link_to post.title, post_path(post.id) -%></h5>
    <p class="card-text"><%= post.body.truncate(100) -%>
        <% if post.body.size >= 10 -%>
        <%= link_to post_path(post.id) do %>
        続きを読む
        <% end %>
        <% end %></p>
  </div>
  <div class="card-footer text-muted">
  <span style="padding-right: 20px;"><i class="far fa-comment-dots"></i>
  <%= link_to"#{post.post_comments.count}", post_path(post.id) %></span>
   <span id="favorite-<%= post.id %>">
   <%= render 'favorites/favorites', post: post %>
   </span>
<% post.tags.each do |tag| %>
   <i class="fas fa-tags"></i><%= tag.name %>
<% end %>

  </div>
</div><br>
<% end %>
<%= paginate posts %>
</div>

app/views/posts/_lanks.html.erb
<div class='col-sm-4 col-md-2'>
  <table class='table'>
    <tr>
      <div class="like">
      <i class="fas fa-heart" style="color: red;"></i>いいねランキング</div>
      <tr></tr><% @all_ranks.each.with_index(1) do |post, i| %>
      <% if i==1 %>
      <th><i class="fas fa-trophy" style="color: gold;"></i></th>
     <% elsif i==2 %>
     <th><i class="fas fa-trophy" style="color: silver;"></i></th>
     <% elsif i==3 %>
     <th><i class="fas fa-trophy" style="color: #BA6E40;"></i></th>
     <% else %>
      <th><%= i %>位</th>
      <% end %>
      <th><%= post.body.truncate(20) -%>
          <% if post.body.size >= 10 -%>
          <%= link_to post_path(post.id) do %>
          続き
          <% end %></th>
          <% end %>
    </tr>
      <% end %>
  </table>
</div>

app/views/posts/edit.html.erb
<div class='container'>
  <div class="row justify-content-center">
    <h1 style="padding-top: 20px;">戦術変更</h1>
  </div>
    <%= flash[:al] %>
    <% if @post.errors.any? %>
      <%= @post.errors.count %>件のエラーが発生しました
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
<%= form_with model: @post, local:true do |f| %>
<div class="form-group">
  <h4>タイトル</h4>
  <%= f.text_field :title, placeholder: "タイトルを入力してください", class: "form-control" %>
</div>
<div class="form-group">
  <h4>タグ</h4>
<%= f.text_field :tag_ids, value: @tag_list, placeholder: "タグをつける。複数つけるには','で区切ってください。", class: "form-control" %>
</div>
<div class="form-group">
  <h4>戦術</h4>
  <%= f.text_area :body, size: "80x10",placeholder: "内容を入力してください", class: "form-control" %>
</div>
<div class="row justify-content-center">
  <%= f.submit '  保存  ', class: "btn btn-sm btn-primary" %>
</div>
<% end %>
<%= link_to :back do %><div style="color: black;">
<i class="fas fa-undo-alt">戻る</i></div>
<% end %>
</div>

app/views/posts/index.html.erb
<div class='container-px-5 px-sm-0'>
  <div class='row'>
    <div class='col-sm-4 col-md-2'>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-sm-4 col-md-8'>
     <%= render 'index', posts: @posts %>
    </div>
      <%= render 'posts/lanks', posts: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 style="padding-top: 20px;">記事を投稿する</h1>
  </div>
    <h5 class="tactics">試合の感想、戦術、選手個々のプレースタイルなどご自由に投稿して下さい。<br>
      WorldTacticsはフットボールに関する知識を記録・共有するためのサービスです。<br>
      投稿者以外の人にとっても価値のある記事であるように意識して投稿してみましょう！
    </h5>
      <%= form_with model: @post, local:true do |f| %>
        <div class="form-group" style="width: 337px;">
          <h4>タイトル</h4>
          <div class="caution">必須</div>
          <%= f.text_field :title, placeholder: "タイトルを入力してください", class: "form-control" %>
        </div>
        <div class="form-group">
          <h4>タグ</h4>
          <%= text_field_tag 'post[tag_ids]', @post.tag_ids, data: {role: "tagsinput"},placeholder: "4つまでタグ付け可能", class: "form-control" %>
        </div>

        <div class="form-group">
          <h4>戦術</h4>
          <div class="caution">必須</div>
          <%= f.text_area :body, size: "80x10",placeholder: "内容を入力してください", class: "form-control" %>
        </div>
        <div class="row justify-content-center">
        <%= f.button '投稿する', type: 'button', onclick: 'submit();', class: "btn btn-lg  btn-primary" %>
        </div>
      <% end %>
      
    <%= link_to :back do %><div style="color: black;">
      <i class="fas fa-undo-alt">戻る</i></div>
    <% end %>
</div>

app/views/posts/show.html.erb
  <%= render 'layouts/errors' %>
  <div class="white" style="padding: 80px 80px 20px 80px;">
    投稿者：<%= @post.user.name %>
    <%= attachment_image_tag @post.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <h3 style="font-weight: bold;">
    タイトル：<%= @post.title %>
  </h5>
<% @post.tags.each do |tag| %>
   <i class="fas fa-tags"></i><%= tag.name %>
<% end %>
  <hr>
  <h6>
  <%=safe_join(@post.body.split("\n"),tag(:br))%>
  </h6>
  <div class="ield form-group mt-2 text-center col-sm-8 offset-sm-2">
    投稿日時：<%= l @post.created_at, format: :short %></div>
  <div class="ield form-group mt-2 text-center col-sm-8 offset-sm-2">
    <% if @post.user == current_user %>
    <%= link_to "編集", edit_post_path(@post), class: "btn btn-sm btn-success" %>
    <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-sm btn-danger" %>
    <% end %>
  </div>
  </div>
<div class="ield form-group mt-2 text-center col-sm-8 offset-sm-2">
  <div id="favorite-<%= @post.id %>">
    <%= render 'favorites/favorites', post: @post %>
  </div>
<%= render 'post_comments/post_comment', post: @post_comment %>
</div>