config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'homes#top'
  get 'homes/about' => "homes#about"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :create, :edit, :update] do
    get "users/follower" => "users#follower"
    get "users/followed" => "users#followed"
    get "users/favorites" => "users#favorites"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :inquiries, only: [:new, :create]

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]

  delete '/notification/destroy_all' => 'notifications#destroy_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  scope :active, -> { order(created_at: :desc) }
  # default_scopeでデフォルトで並び順を作成日降順にしてるので常に新しい通知からデータから取ってこれる

  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
  # optional:trueでnillを許可
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships

  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tags(savepost_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      tags << post_tag
    end
  end

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorite"
    )
    notification.save if notification.valid?
    # valid？でバリデーションが実行された結果エラーが無い場合trueを返し，エラーが発生した場合falseを返す
  end

  def create_notification_comment!(current_user, post_comment_id) # 感嘆符で例外を発生させる
    # 自分以外にコメントしている人を全て取得し全員に通知送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).
      where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合投稿者に通知送る
    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )

    # 自分の投稿に対しては通知ずみとする
    if notification.visiter_id == notification.visited_id
      notification.checked == true
    end
    notification.save if notification.valid?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats, dependent: :destroy
  has_many :user_rooms
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, dependent: :destroy
  has_many :posts, through: :tag_relationships
  validates :name, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  attachment :profile_image

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :follower_user, through: :followed, source: :follower
  has_many :following_user, through: :follower, source: :followed
  # foreign_keyは入口  sourceは出口

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :room, through: :user_rooms

  has_many :active_notifications, class_name: "Notification",
                                  foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
                                   foreign_key: "visited_id", dependent: :destroy

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # すでにフォロー済みであればtrue返す
  def following?(user)
    following_user.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def create_notification_follow!(current_user)
    # 同じ通知が存在しない時だけレコードを作成
    temp = Notification.where([
      "visiter_id = ? and visited_id = ? and action = ? ",
      current_user.id, id, 'follow',
    ])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "primary"
    when "error"
      "danger"
    end
  end
end

app/views/layouts/_errors.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <% @post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key)%> close-flash">
    <%= value %>
    <button type="button" class="close close-button" data-dismiss="alert">
      &times;
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright © 2021 WorldTactics</p>
</footer>

app/views/layouts/_header.html.erb
<div class="fixed-top">
<header class="mb-auto">
  <div class="header">
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>World Tactics</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
         <li><%= link_to '戦術投稿フォーム', new_post_path,class: 'fas fa-plus'%></li>
         <li><%= link_to '戦術投稿一覧', posts_path,class: 'fas fa-futbol' %></li>
         <li><%= link_to 'ユーザー一覧', users_path,class: 'fas fa-users' %></li>
         <li><%= link_to 'マイページ', user_path(current_user.id),class: 'fas fa-user' %></li>
         <li><%= link_to 'お問い合わせ', new_inquiry_path,class: 'fas fa-envelope' %></li>
         <% if unchecked_notifications.any? %>
           <i class="fas fa-circle"></i>
          <% end %>
         <li><%= link_to "通知", notifications_path, class: 'fas fa-bell ' %></li>
         <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt' %></li>
      <% else %>
         <li><%= link_to '投稿一覧', posts_path,class: 'fas fa-futbol' %></li>
         <li><%= link_to 'About', homes_about_path,class: 'fas fa-link'%></li>
         <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'fas fa-link'%></li>
    <% end %>
        </ul>
      </div>
    </div>
    </div>
    </div>
  </nav>
</header>
 </div>

app/views/layouts/_lanks.html.erb
<div class='col-sm-4 col-md-2'>
  <table class='table'>
    <tr>
    <div class="like">
     <i class="fas fa-star" style="color: gold;"></i>いいねランキング</div>
      <% @all_ranks.each.with_index(1) do |post, i| %>
      <th><%= i %>位</th>
      <th><%= post.body.truncate(20) -%>
        <% if post.body.size >= 10 -%>
        <%= link_to post_path(post.id) do %>
        続き
        <% end %></th>
        <% end %>
    </tr>
      <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldTactics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('icon2.png') %>
  </head>
  <body>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
   <%= render 'layouts/header' %>
     <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>